//===============================================================================
//All programming code examples associated with Real World Software Configuration
//Management are copyright 2003 by Sean Kenefick unless otherwise automatically
//generated by a tool (in which case its copyright is held by the applicable
//tool vendor).
//===============================================================================

using System.Reflection;
using System.Runtime.CompilerServices;

//
// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
//
[assembly: AssemblyCompany("cmReady Ssytems Incorporated")]
[assembly: AssemblyProduct("The Stock Program")]
[assembly: AssemblyCopyright("(c) 2003 cmReady Ssytems Incorporated ")]

//
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:

[assembly: AssemblyVersion("2.1.*")]
