//===============================================================================
//All programming code examples associated with Real World Software Configuration
//Management are copyright 2003 by Sean Kenefick unless otherwise automatically
//generated by a tool (in which case its copyright is held by the applicable
//tool vendor).
//===============================================================================

using System;
using System.IO;

namespace SETUP_SS
{
     /// <summary>
     /// Summary description for Class1.
     /// </summary>
     class Class1
     {
          /// <summary>
          /// The main entry point for the application.
          /// </summary>
          [STAThread]
          static void Main(string[] args)
          {
               foreach (string s in args)
               {
                    switch (s)
                    {
                         case "install":
                              install();
                              break;

                         case "commit":
                              commit();
                              break;

                         case "rollback":
                              rollback();
                              break;

                         case "uninstall":
                              uninstall();
                              break;
                    }
               }
          }

          static void install()
          {
               TextWriter tx = new StreamWriter("C:\\SETUP_SS.TXT", true,  System.Text.Encoding.Default);
               tx.WriteLine("The \"install\" custom action has been called.");
               tx.Close();
          }

          static void commit()
          {
               TextWriter tx = new StreamWriter("C:\\SETUP_SS.TXT", true,  System.Text.Encoding.Default);
               tx.WriteLine("The \"commit\" custom action has been called.");
               tx.Close();
          }
     
          static void rollback()
          {
               TextWriter tx = new StreamWriter("C:\\SETUP_SS.TXT", true, System.Text.Encoding.Default);
               tx.WriteLine("The \"rollback\" custom action has been called.");
               tx.Close();
          }
     
          static void uninstall()
          {
               TextWriter tx = new StreamWriter("C:\\SETUP_SS.TXT", true, System.Text.Encoding.Default);
               tx.WriteLine("The \"uninstall\" custom action has been called.");
               tx.Close();
          }
     }
}
