//===============================================================================
//All programming code examples associated with Real World Software Configuration
//Management are copyright 2003 by Sean Kenefick unless otherwise automatically
//generated by a tool (in which case its copyright is held by the applicable
//tool vendor).
//===============================================================================

#include <stdio.h>

int main()
{
     printf("An RPM example!\n");
}

