//===============================================================================
//All programming code examples associated with Real World Software Configuration
//Management are copyright 2003 by Sean Kenefick unless otherwise automatically
//generated by a tool (in which case its copyright is held by the applicable
//tool vendor).
//===============================================================================

#include <stdio.h>
int main()
{
     char szName[128];
     printf( "\n\nPlease enter your name: " );
     gets( szName );
     printf("Hello %s!  Welcome to the RPM example!\n\n", szName);
}

