#===============================================================================
#All programming code examples associated with Real World Software Configuration
#Management are copyright 2003 by Sean Kenefick unless otherwise automatically
#generated by a tool (in which case its copyright is held by the applicable
#tool vendor).
#===============================================================================

#
# Example spec file RPM-Example...
#
Summary: A program that does absolutely nothing but demonstrate RPM!
Name: rpm-example
Version: 1.0
Release: 1
Copyright: GPL
Group: Applications/Sound
Source: rpm-example.tar.gz
URL: http://www.cmready.com
Distribution: Example Linux
Vendor: cmReady, Inc.
Packager: Sean Kenefick <skenefick@cmready.com>

%description
It really does nothing except show how RPM works.  Really.  That's
all.  I don't suggest running it unless you wish to see it work.

%prep
rm -rf $RPM_BUILD_DIR/rpm-example
zcat $RPM_SOURCE_DIR/rpm-example.tar.gz | tar -xvf -

%build
cd $RPM_BUILD_DIR/rpm-example
make

%install
cd $RPM_BUILD_DIR/rpm-example
make install

%files
/usr/bin/welcome_rpm_example
/usr/bin/hello_rpm_example
